wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 64
hidden_layers_count:
  value: 2
learning_rate:
  value: 0.01
loss:
  value: cross_entropy_loss
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: he
