wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 64
hidden_layers_count:
  value: 2
learning_rate:
  value: 0.1
loss:
  value: mean_squared_error
optimizer:
  value: sgd
weight_decay:
  value: 0.005
weight_init:
  value: random
