wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 2
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.0001
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
