wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 2
hidden_layer_size:
  value: 64
hidden_layers_count:
  value: 5
learning_rate:
  value: 0.001
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: random
