wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.1
loss:
  value: mean_squared_error
optimizer:
  value: nesterov
weight_decay:
  value: 0.005
weight_init:
  value: he
