wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.1
loss:
  value: cross_entropy_loss
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: he
