wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 256
hidden_layers_count:
  value: 2
learning_rate:
  value: 0.1
loss:
  value: mean_squared_error
optimizer:
  value: momentum
weight_decay:
  value: 0.005
weight_init:
  value: he
