wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 256
hidden_layers_count:
  value: 2
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: he
