wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 2
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error
optimizer:
  value: nesterov
weight_decay:
  value: 0
weight_init:
  value: random
