_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 64
epochs:
    value: 5
hidden_layers:
    value:
        - 128
        - 64
learning_rate:
    value: 0.001
optimizer:
    value: momentum
