wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 2
hidden_layer_size:
  value: 64
hidden_layers_count:
  value: 5
learning_rate:
  value: 0.0001
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
