_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 2
                - 3
                - 55
                - 105
            "2":
                - 2
                - 3
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 16
epochs:
    value: 2
hidden_layer_size:
    value: 64
hidden_layers_count:
    value: 5
learning_rate:
    value: 0.0001
optimizer:
    value: momentum
weight_decay:
    value: 0.0005
weight_init:
    value: xavier
