wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 40
hidden_layer_size:
  value: 256
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.001
loss:
  value: cross_entropy_loss
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: he
