wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 256
hidden_layers_count:
  value: 2
learning_rate:
  value: 0.1
loss:
  value: cross_entropy_loss
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: random
