wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 128
hidden_layers_count:
  value: 3
learning_rate:
  value: 0.001
loss:
  value: cross_entropy_loss
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: he
