wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 128
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.01
loss:
  value: cross_entropy_loss
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: he
