wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 128
hidden_layers_count:
  value: 3
learning_rate:
  value: 0.01
loss:
  value: cross_entropy_loss
optimizer:
  value: nesterov
weight_decay:
  value: 0.0005
weight_init:
  value: he
