wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 256
hidden_layers_count:
  value: 2
learning_rate:
  value: 0.1
loss:
  value: cross_entropy_loss
optimizer:
  value: nadam
weight_decay:
  value: 0.005
weight_init:
  value: he
