wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 15
hidden_layer_size:
  value: 128
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy_loss
optimizer:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: he
