wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 64
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: random
