wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 64
hidden_layers_count:
  value: 5
learning_rate:
  value: 0.0001
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: xavier
