wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 5
learning_rate:
  value: 0.001
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: xavier
