wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 2
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 3
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: random
