wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 3
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy_loss
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: he
