wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 256
hidden_layers_count:
  value: 5
learning_rate:
  value: 0.001
loss:
  value: cross_entropy_loss
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: xavier
