wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 2
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 3
learning_rate:
  value: 0.0001
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: he
