_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 2
                - 3
                - 55
                - 105
            "2":
                - 2
                - 3
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 64
epochs:
    value: 5
hidden_layers:
    value:
        - 128
        - 64
learning_rate:
    value: 0.001
optimizer:
    value: sgd
