_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.0
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 24
                - 55
            "4": 3.8.0
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 16
epochs:
    value: 10
hidden_layer_size:
    value: 32
hidden_layers_count:
    value: 3
learning_rate:
    value: 0.1
loss:
    value: mean_squared_error
optimizer:
    value: rmsprop
weight_decay:
    value: 0
weight_init:
    value: xavier
