wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 2
learning_rate:
  value: 0.001
loss:
  value: cross_entropy_loss
optimizer:
  value: nesterov
weight_decay:
  value: 0.005
weight_init:
  value: he
