_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 24
                - 55
            "4": 3.10.13
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: tanh
batch_size:
    value: 16
epochs:
    value: 5
hidden_layer_size:
    value: 128
hidden_layers_count:
    value: 4
learning_rate:
    value: 0.1
loss:
    value: cross_entropy_loss
optimizer:
    value: nesterov
weight_decay:
    value: 0.0005
weight_init:
    value: he
