wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 2
hidden_layer_size:
  value: 256
hidden_layers_count:
  value: 2
learning_rate:
  value: 0.001
loss:
  value: cross_entropy_loss
optimizer:
  value: rmsprop
weight_decay:
  value: 0.005
weight_init:
  value: xavier
