_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.0
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 24
                - 55
            "4": 3.8.0
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 16
epochs:
    value: 10
hidden_layer_size:
    value: 128
hidden_layers_count:
    value: 4
learning_rate:
    value: 0.001
loss:
    value: cross_entropy_loss
optimizer:
    value: momentum
weight_decay:
    value: 0.5
weight_init:
    value: he
