wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: he
