wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 64
hidden_layers_count:
  value: 3
learning_rate:
  value: 0.1
loss:
  value: mean_squared_error
optimizer:
  value: rmsprop
weight_decay:
  value: 0.005
weight_init:
  value: he
