wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 32
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.0001
optimizer:
  value: momentum
weight_decay:
  value: 0.5
weight_init:
  value: xavier
