wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 64
hidden_layers_count:
  value: 4
learning_rate:
  value: 0.0001
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
